languageCode = "en"
title = "Stanislav Myachenkov"
theme = "hugo-kiera"
baseURL = 'https://smyachenkov.com/'
googleAnalytics = "UA-136218929-1"
enableRobotsTXT = true
enableEmoji = true
disqusShortname = "smyachenkov"
showShareIcons = true
enableGitInfo = false
paginate = 5
summaryLength = 30
CommentAutoload = true

pygmentsstyle = "dracula"
pygmentsuseclasses = false
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[author]
    name = "Stanislav Myachenkov"
    github = "smyachenkov"
    linkedin = "stanislav-myachenkov"
    instagram = "s.myachenkov" 
    email = "mailto:s.myachenkov@gmail.com"
    telegram = "smyachenkov"

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  tagline = "Notes about programming and dev culture."
  featherIconsCDN = true
  mode = "auto"
  disableDisqusTypes = ["page"]
  customCSS  = ["css/links.css"]
  customDarkCSS = ["css/links-dark.css"]

[taxonomies]
  tag = "tags"

# Header Menu
[[menu.main]]
name = "Posts"
url = "/"
weight = 1

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3