languageCode = "en-us"
title = "Stanislav Myachenkov"
theme = "ezhil"
baseURL = 'https://smyachenkov.com/'
googleAnalytics = "UA-136218929-1"
enableRobotsTXT = true
disqusShortname = "smyachenkov"
showShareIcons = true
paginate = 5

pygmentsstyle = "pastie"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  subtitle = "Notes about programming, software engineering and computer science."
  featherIconsCDN = true
  mode = "auto"
  disableDisqusTypes = ["page"]
  customCSS  = "css/links.css"
  customDarkCSS = "css/links-dark.css"

[taxonomies]
  tag = "tags"

[[params.social]]
  name = "Email"
  icon = "mail"
  url = "mailto:s.myachenkov@gmail.com"

[[params.social]]
  name = "Telegram"
  icon = "send"
  url = "https://t.me/smyachenkov"

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/smyachenkov/"

[[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https://www.instagram.com/s.myachenkov/"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/stanislav-myachenkov/"

# Header Menu
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
