languageCode = "en-us"
title = "smyachenkov"
theme = "whiteplain"
baseURL = 'http://smyachenkov.com/'
googleAnalytics = "UA-136218929-1"
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params.author]
  name = "Stanislav Myachenkov"
  instagram = "flslkxtc"
  linkedin = "stanislav-myachenkov-560a2678"
  github = "smyachenkov"
  foursquare = "flslkxtc"
  telegram = "smyachenkov"
  avatar = "avatar.jpg"

# Header Menu
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 1
[[menu.main]]
  name = "About Me"
  identifier = "about"
  url = "/about/"
  weight = 2

# Footer Menu
[[menu.footer]]
  name = "About Me"
  weight = 1
  identifier = "about me"
  url = "/about/"